--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_BOARD_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 27 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."BOARD" 
   (	"NUM" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"ID" VARCHAR2(10 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate, 
	"VISITCOUNT" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."MEMBER" 
   (	"ID" VARCHAR2(10 BYTE), 
	"PASS" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"REGIDATE" DATE DEFAULT sysdate, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WEBPROJECT_DB"."MEMBER" TO "WEBPROJECT";
  GRANT DELETE ON "WEBPROJECT_DB"."MEMBER" TO "WEBPROJECT";
  GRANT INSERT ON "WEBPROJECT_DB"."MEMBER" TO "WEBPROJECT";
  GRANT UPDATE ON "WEBPROJECT_DB"."MEMBER" TO "WEBPROJECT";
--------------------------------------------------------
--  DDL for Table MVCBOARD_DATA
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."MVCBOARD_DATA" 
   (	"IDX" NUMBER, 
	"ID" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"OFILE" VARCHAR2(100 BYTE), 
	"SFILE" VARCHAR2(100 BYTE), 
	"POSTDATE" DATE DEFAULT SYSDATE, 
	"VISITCOUNT" NUMBER DEFAULT 0, 
	"DOWNCOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MVCBOARD_FREE
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."MVCBOARD_FREE" 
   (	"IDX" NUMBER, 
	"ID" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"POSTDATE" DATE DEFAULT SYSDATE, 
	"VISITCOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MVCBOARD_NOTICE
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."MVCBOARD_NOTICE" 
   (	"IDX" NUMBER, 
	"ID" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"OFILE" VARCHAR2(100 BYTE), 
	"SFILE" VARCHAR2(100 BYTE), 
	"POSTDATE" DATE DEFAULT SYSDATE, 
	"VISITCOUNT" NUMBER DEFAULT 0, 
	"DOWNCOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
REM INSERTING into WEBPROJECT_DB.BOARD
SET DEFINE OFF;
Insert into WEBPROJECT_DB.BOARD (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT) values (2,'제목1입니다','내용1입니다','musthave',to_date('25/12/05','RR/MM/DD'),0);
Insert into WEBPROJECT_DB.BOARD (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT) values (3,'제목1입니다','내용1입니다','musthave',to_date('25/12/05','RR/MM/DD'),0);
Insert into WEBPROJECT_DB.BOARD (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT) values (4,'제목1입니다','내용1입니다','musthave',to_date('25/12/05','RR/MM/DD'),0);
Insert into WEBPROJECT_DB.BOARD (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT) values (5,'제목1입니다','내용1입니다','musthave',to_date('25/12/05','RR/MM/DD'),0);
REM INSERTING into WEBPROJECT_DB.MEMBER
SET DEFINE OFF;
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,REGIDATE,EMAIL,PHONE) values ('musthave','1234','머스트해브',to_date('25/12/05','RR/MM/DD'),null,null);
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,REGIDATE,EMAIL,PHONE) values ('webproject','1234','웹프로젝트',to_date('25/12/05','RR/MM/DD'),null,null);
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,REGIDATE,EMAIL,PHONE) values ('qwer','1234','홍길동',to_date('25/12/12','RR/MM/DD'),'korea@naver.com','010-8888-8888');
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,REGIDATE,EMAIL,PHONE) values ('aaaa','1234','홍길동',to_date('25/12/08','RR/MM/DD'),'korea@naver.com','010-1234-5678');
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,REGIDATE,EMAIL,PHONE) values ('1111','1234','홍길동',to_date('25/12/08','RR/MM/DD'),'korea@naver.com','010-1234-5678');
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,REGIDATE,EMAIL,PHONE) values ('2222','1234','2222',to_date('25/12/09','RR/MM/DD'),'korea@naver.com','010-1234-5678');
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,REGIDATE,EMAIL,PHONE) values ('9999','1234','홍길동',to_date('25/12/12','RR/MM/DD'),'korea@naver.com','010-1234-5678');
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,REGIDATE,EMAIL,PHONE) values ('1234','1234','홍길동',to_date('25/12/08','RR/MM/DD'),'korea@naver.com','010-1234-5678');
REM INSERTING into WEBPROJECT_DB.MVCBOARD_DATA
SET DEFINE OFF;
Insert into WEBPROJECT_DB.MVCBOARD_DATA (IDX,ID,TITLE,OFILE,SFILE,POSTDATE,VISITCOUNT,DOWNCOUNT) values (22,'1234','2222222','3.jpg','20251211_155515775.jpg',to_date('25/12/11','RR/MM/DD'),0,0);
Insert into WEBPROJECT_DB.MVCBOARD_DATA (IDX,ID,TITLE,OFILE,SFILE,POSTDATE,VISITCOUNT,DOWNCOUNT) values (21,'1234','0000','2.jpg','20251211_93147870.jpg',to_date('25/12/11','RR/MM/DD'),9,0);
Insert into WEBPROJECT_DB.MVCBOARD_DATA (IDX,ID,TITLE,OFILE,SFILE,POSTDATE,VISITCOUNT,DOWNCOUNT) values (23,'1234','erfggf','4.jpg','20251211_155521999.jpg',to_date('25/12/11','RR/MM/DD'),0,0);
Insert into WEBPROJECT_DB.MVCBOARD_DATA (IDX,ID,TITLE,OFILE,SFILE,POSTDATE,VISITCOUNT,DOWNCOUNT) values (24,'1234','2efqaeq4q4ed','2.jpg','20251211_155531110.jpg',to_date('25/12/11','RR/MM/DD'),16,0);
Insert into WEBPROJECT_DB.MVCBOARD_DATA (IDX,ID,TITLE,OFILE,SFILE,POSTDATE,VISITCOUNT,DOWNCOUNT) values (26,'9999','반갑습니다','4.jpg','20251212_101016394.jpg',to_date('25/12/12','RR/MM/DD'),0,0);
REM INSERTING into WEBPROJECT_DB.MVCBOARD_FREE
SET DEFINE OFF;
Insert into WEBPROJECT_DB.MVCBOARD_FREE (IDX,ID,TITLE,POSTDATE,VISITCOUNT) values (15,'1234','안녕하세요',to_date('25/12/10','RR/MM/DD'),0);
Insert into WEBPROJECT_DB.MVCBOARD_FREE (IDX,ID,TITLE,POSTDATE,VISITCOUNT) values (17,'1234','ㅂㅈㄷㄱㅂㄷㄱ',to_date('25/12/10','RR/MM/DD'),0);
Insert into WEBPROJECT_DB.MVCBOARD_FREE (IDX,ID,TITLE,POSTDATE,VISITCOUNT) values (18,'1234','1234',to_date('25/12/10','RR/MM/DD'),0);
Insert into WEBPROJECT_DB.MVCBOARD_FREE (IDX,ID,TITLE,POSTDATE,VISITCOUNT) values (19,'1234','12341234',to_date('25/12/10','RR/MM/DD'),21);
REM INSERTING into WEBPROJECT_DB.MVCBOARD_NOTICE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008423
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008423" ON "WEBPROJECT_DB"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008428
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008428" ON "WEBPROJECT_DB"."BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008441
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008441" ON "WEBPROJECT_DB"."MVCBOARD_FREE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008445
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008445" ON "WEBPROJECT_DB"."MVCBOARD_DATA" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008449
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008449" ON "WEBPROJECT_DB"."MVCBOARD_NOTICE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008428
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008428" ON "WEBPROJECT_DB"."BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008423
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008423" ON "WEBPROJECT_DB"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008445
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008445" ON "WEBPROJECT_DB"."MVCBOARD_DATA" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008441
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008441" ON "WEBPROJECT_DB"."MVCBOARD_FREE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008449
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008449" ON "WEBPROJECT_DB"."MVCBOARD_NOTICE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("REGIDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MVCBOARD_DATA
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."MVCBOARD_DATA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MVCBOARD_DATA" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MVCBOARD_DATA" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MVCBOARD_DATA" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MVCBOARD_FREE
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."MVCBOARD_FREE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MVCBOARD_FREE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MVCBOARD_FREE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MVCBOARD_FREE" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MVCBOARD_NOTICE
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."MVCBOARD_NOTICE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MVCBOARD_NOTICE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MVCBOARD_NOTICE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MVCBOARD_NOTICE" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD" ADD CONSTRAINT "BOARD_MEM_FK" FOREIGN KEY ("ID")
	  REFERENCES "WEBPROJECT_DB"."MEMBER" ("ID") ENABLE;
